name: EigenFold CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyTorch and PyG dependencies
        run: |
          pip install torch==1.11.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cu113.html

      - name: Install other Python dependencies
        run: |
          pip install e3nn pyyaml wandb biopython matplotlib pandas flake8

      - name: Install OmegaFold dependency
        run: |
          git clone https://github.com/bjing2016/OmegaFold.git
          pip install --no-deps -e ./OmegaFold

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run help commands on main scripts
        run: |
          python EigenFold/train.py --help
          python EigenFold/inference.py --help
          python EigenFold/make_splits.py --help
          python EigenFold/unpack_pdb.py --help
          python EigenFold/make_embeddings.py --help

      - name: Run training script in dry run mode
        run: |
          # This test requires a dummy splits file and a dummy embeddings directory
          mkdir -p ./data/embeddings/du/
          python EigenFold/train.py --dry_run --splits dummy_split.csv --pdb_dir /tmp --embeddings_dir ./data/embeddings
